### ISSUE TITLE
Missing implementation PhoneNumberToCarrierMapper

### ISSUE THREAD

**Issue by cm-gb** [jarroda/libphonenumber-dotnet#2]
I can't find the implementation of the PhoneNumberToCarrierMapper class. Has it not been ported yet?

**Comment by jarroda** [comment]
This project is a port to .net of a previous project (see the wiki for a link) which ported Google's libphonenumber library to C#.  However, the previous project has not had an update in over a year, and is quite out of date.  My guess is this feature of the library never made it over in the original port.

I would love to create a new port directly from the current java source, but I don't currently have the time.  I would be happy to take contributions though. :-D

**Comment by cm-gb** [comment]
Yes, I understand. Thanks for replying. Unfortunately, I don't have much time either :(.
